# Generated by Django 5.2.1 on 2025-11-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
