# Generated by Django 5.2.1 on 2025-11-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customerprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
