# Generated by Django 5.2.1 on 2025-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customerprofile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
